/* config.h.  Generated by cmake from config.h.cmake */

#define VERSION "1.5"

#cmakedefine CONFIG_USE_KDE 1

/* Define if you have id3lib installed */
#cmakedefine HAVE_ID3LIB 1
#cmakedefine HAVE_NO_ID3LIB_VBR

/* Define if you have TagLib installed */
#cmakedefine HAVE_TAGLIB 1

/* Define if you have mp4v2 installed */
#cmakedefine HAVE_MP4V2 1

/* Define if you have mp4v2/mp4v2.h installed */
#cmakedefine HAVE_MP4V2_MP4V2_H 1

/* Define to build with MP4GetMetadataByIndex char** argument */
#cmakedefine HAVE_MP4V2_MP4GETMETADATABYINDEX_CHARPP_ARG 1

/* Set to TunePimp version, undefined if not installed */
#cmakedefine HAVE_TUNEPIMP ${HAVE_TUNEPIMP}

/* Define if you have ogg/vorbis installed */
#cmakedefine HAVE_VORBIS 1

/* Define if you have FLAC++ installed */
#cmakedefine HAVE_FLAC 1
#cmakedefine HAVE_NO_FLAC_STREAMMETADATA_OPERATOR
#cmakedefine HAVE_FLAC_PICTURE 1

/* Define if you have QtDBus installed */
#cmakedefine HAVE_QTDBUS 1

/* Define if you have Phonon installed */
#cmakedefine HAVE_PHONON 1
