/* config.h.  Generated by cmake from config.h.cmake */

#define VERSION "0.9"

#cmakedefine CONFIG_USE_KDE 1

/* Define if you have id3lib installed */
#cmakedefine HAVE_ID3LIB 1
#cmakedefine HAVE_NO_ID3LIB_VBR

/* Define if you have TagLib installed */
#cmakedefine HAVE_TAGLIB 1

/* Set to TunePimp version, undefined if not installed */
#cmakedefine HAVE_TUNEPIMP ${HAVE_TUNEPIMP}

/* Define if you have ogg/vorbis installed */
#cmakedefine HAVE_VORBIS 1

/* Define if you have FLAC++ installed */
#cmakedefine HAVE_FLAC 1
#cmakedefine HAVE_NO_FLAC_STREAMMETADATA_OPERATOR
