# SPDX-FileCopyrightText: 2024, 2025 Scarlett Moore <sgmoore@kde.org>
#
# SPDX-License-Identifier: CC0-1.0
---
name: kid3
confinement: strict
grade: stable
base: core24
adopt-info: kid3
apps:
  kid3:
    extensions:
      - kde-neon-6
    common-id: org.kde.kid3.desktop
    desktop: usr/share/applications/org.kde.kid3.desktop
    command: usr/bin/kid3
    plugs:
        - home
        - audio-playback
        - mpris
    environment:
      CFG_QMLDIR: "$SNAP/usr/share/kid3/qml"
      LD_LIBRARY_PATH: $SNAP/ffmpeg-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$SNAP/usr/lib/kid3:${LD_LIBRARY_PATH}
      PATH: $SNAP/ffmpeg-platform/usr/bin:${PATH}
plugs:
  ffmpeg-2404:
    interface: content
    target: ffmpeg-platform # the folder where this content snap will be mounted
    default-provider: ffmpeg-2404
layout:
    "/usr/lib/$CRAFT_ARCH_TRIPLET/alsa-lib":
        bind: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/alsa-lib"
    "/usr/share/alsa":
        bind: "$SNAP/usr/share/alsa"
slots:
  mpris:
    interface: dbus
    name: org.mpris.MediaPlayer2.kid3
    bus: session
parts:
  kid3:
    parse-info:
      - usr/share/metainfo/org.kde.kid3.appdata.xml
    plugin: cmake
    build-packages:
      - libid3-3.8.3-dev
      - libflac++-dev
      - libvorbis-dev
      - libtag1-dev
      - libchromaprint-dev
      - libreadline-dev
      - xsltproc
      - python3
      - libgstreamer1.0-dev
      - libxkbcommon-dev
    build-snaps:
      - ffmpeg-2404-sdk
    stage-packages:
      - libxinerama1
      - libid3-3.8.3v5
      - libflac++10
      - libxkbcommon0
    source: .
    source-type: local
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DBUILD_WITH_QT6=ON
      - -DBUILD_TESTING=OFF
    build-environment:
      - PYTHONPATH: ${CRAFT_STAGE}/lib/python3.12/site-packages:${CRAFT_STAGE}/usr/lib/python3/dist-packages
    prime:
      - "-usr/lib/*/cmake/*"
      - "-usr/include/*"
      - "-usr/share/ECM/*"
      - "-usr/share/doc/*"
      - "-usr/share/man/*"
      - "-usr/bin/X11"
      - "-usr/lib/gcc/$CRAFT_ARCH_TRIPLET/6.0.0"
      - "-usr/lib/aspell/*"
      - "-usr/share/lintian"
  gpu-2404:
    after: [kid3]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
    prime:
      - bin/gpu-2404-wrapper
  cleanup:
    after:
      - kid3
    plugin: nil
    build-snaps:
      - core24
      - kf6-core24
      - ffmpeg-2404
    override-prime: |
      set -eux
      for snap in "core24" "kf6-core24" "ffmpeg-2404"; do
        cd "/snap/$snap/current" && find . -type f,l -exec rm -rf "${CRAFT_PRIME}/{}" \;
      done
