set(app_QML_SRCS
  app/Main.qml
  app/MainPage.qml
  app/Collapsible.qml
  app/ComboBox.qml
  app/DropDownList.qml
  app/FrameDelegate.qml
  app/FrameEditDialog.qml
  app/FrameSelectDialog.qml
  app/MessageDialog.qml
  app/ActionSelectionDelegate.qml
  app/UiConstants.qml
  app/FileList.qml
  app/FileCollapsible.qml
  app/TagCollapsible.qml
  app/PictureCollapsible.qml
  app/FileSelectDialog.qml
  app/RenameDirectoryPage.qml
  app/NumberTracksDialog.qml
  app/FilterPage.qml
  app/BatchImportPage.qml
  app/AbstractSettingsPage.qml
  app/SettingsElement.qml
  app/SettingsPage.qml
  app/SettingsItem.qml
  app/RaisableRectangle.qml
  app/AboutDialog.qml
)
