/* oggflacconfig.h.  Generated by cmake from oggflacconfig.h.cmake */
#ifndef OGGFLACCONFIG_H
#define OGGFLACCONFIG_H

/* Define if you have ogg/vorbis installed */
#cmakedefine HAVE_VORBIS 1

/* Define if you have FLAC++ installed */
#cmakedefine HAVE_FLAC 1
#cmakedefine HAVE_NO_FLAC_STREAMMETADATA_OPERATOR
#cmakedefine HAVE_FLAC_PICTURE 1

#endif
