/* mp4v2config.h.  Generated by cmake from mp4v2config.h.cmake */
#ifndef MP4V2CONFIG_H
#define MP4V2CONFIG_H

/* Define if you have mp4v2/mp4v2.h installed */
#cmakedefine HAVE_MP4V2_MP4V2_H 1

/* Define to build with MP4GetMetadataByIndex char** argument */
#cmakedefine HAVE_MP4V2_MP4GETMETADATABYINDEX_CHARPP_ARG 1

#endif
