set(config_SRCS
  config/amazonconfig.cpp
  config/batchimportconfig.cpp
  config/batchimportprofile.cpp
  config/batchimportsourcesmodel.cpp
  config/configstore.cpp
  config/discogsconfig.cpp
  config/filterconfig.cpp
  config/formatconfig.cpp
  config/freedbconfig.cpp
  config/generalconfig.cpp
  config/importconfig.cpp
  config/miscconfig.cpp
  config/musicbrainzconfig.cpp
  config/playlistconfig.cpp
  config/serverimporterconfig.cpp
  config/shortcutsmodel.cpp
)

set(config_MOC_HDRS
  config/batchimportsourcesmodel.h
  config/shortcutsmodel.h
)
