/* acoustidconfig.h.  Generated by cmake from acoustidconfig.h.cmake */
#ifndef ACOUSTIDCONFIG_H
#define ACOUSTIDCONFIG_H

/* Define if avresample is available */
#cmakedefine HAVE_AVRESAMPLE ${HAVE_AVRESAMPLE}

/* Define if av_audio_convert is available */
#cmakedefine HAVE_AV_AUDIO_CONVERT ${HAVE_AV_AUDIO_CONVERT}

#endif
