/* acoustidconfig.h.  Generated by cmake from acoustidconfig.h.cmake */
#pragma once

/* Define if avresample is available */
#cmakedefine HAVE_AVRESAMPLE ${HAVE_AVRESAMPLE}

/* Define if swresample is available */
#cmakedefine HAVE_SWRESAMPLE ${HAVE_SWRESAMPLE}

/* Define if av_audio_convert is available */
#cmakedefine HAVE_AV_AUDIO_CONVERT ${HAVE_AV_AUDIO_CONVERT}
