/**
 * \file id3form.h
 * GUI for kid3, originally generated by QT Designer.
 *
 * \b Project: Kid3
 * \author Urs Fleisch
 * \date 8 Apr 2003
 */

#ifndef ID3FORM_H
#define ID3FORM_H

#include <qvariant.h>
#include <qsplitter.h>
#include "filelist.h"

class QVBoxLayout;
class QGridLayout;
class QCheckBox;
class QComboBox;
class QGroupBox;
class QLabel;
class QLineEdit;
class QListBox;
class QListBoxItem;
class QPushButton;
class QSpinBox;
class QSplitter;
class QScrollView;
class QVBox;
class QHBox;
class StandardTags;
class Kid3ScrollView;

class id3Form : public QSplitter
{
    Q_OBJECT

public:
    id3Form(QWidget* parent = 0, const char* name = 0);

    FileList *mp3ListBox;
    QComboBox* genreV1ComboBox;
    QComboBox* genreV2ComboBox;
    QComboBox* formatComboBox;
    QLineEdit* nameLineEdit;
    QListBox* framesListBox;

public slots:
    virtual void fromFilenameV1();
    virtual void fromFilenameV2();
    virtual void fromID3V2();
    virtual void fromID3V1();
    virtual void copyV1();
    virtual void copyV2();
    virtual void removeV2();
    virtual void pasteV1();
    virtual void pasteV2();
    virtual void removeV1();
    virtual void fileSelected(void);
    virtual void getStandardTagsV1(StandardTags * st);
    virtual void getStandardTagsV2(StandardTags * st);
    virtual void setStandardTagsV1(const StandardTags * st);
    virtual void setStandardTagsV2(const StandardTags * st);
    virtual void setAllCheckBoxes(bool val);
    virtual int numFilesSelected();
    virtual void editFrame(void);
    virtual void addFrame(void);
    virtual void deleteFrame(void);
    virtual void fnFromID3V1(void);
    virtual void fnFromID3V2(void);

private:
    QGroupBox* filenameGroupBox;
    QLabel* nameLabel;
    QPushButton* fnV1Button;
    QPushButton* fnV2Button;
    QLabel* formatLabel;
    QGroupBox* idV1GroupBox;
    QLineEdit* albumV1LineEdit;
    QPushButton* copyV1PushButton;
    QPushButton* filenameV1PushButton;
    QLineEdit* artistV1LineEdit;
    QPushButton* removeV1PushButton;
    QPushButton* pasteV1PushButton;
    QCheckBox* albumV1CheckBox;
    QCheckBox* yearV1CheckBox;
    QLineEdit* titleV1LineEdit;
    QSpinBox* yearV1SpinBox;
    QCheckBox* trackV1CheckBox;
    QSpinBox* trackV1SpinBox;
    QPushButton* id3V1PushButton;
    QCheckBox* titleV1CheckBox;
    QCheckBox* genreV1CheckBox;
    QCheckBox* commentV1CheckBox;
    QCheckBox* artistV1CheckBox;
    QLineEdit* commentV1LineEdit;
    QGroupBox* idV2GroupBox;
    QPushButton* copyV2PushButton;
    QCheckBox* commentV2CheckBox;
    QLineEdit* titleV2LineEdit;
    QLineEdit* albumV2LineEdit;
    QLineEdit* artistV2LineEdit;
    QPushButton* pasteV2PushButton;
    QCheckBox* genreV2CheckBox;
    QLineEdit* commentV2LineEdit;
    QPushButton* filenameV2PushButton;
    QPushButton* removeV2PushButton;
    QCheckBox* yearV2CheckBox;
    QPushButton* id3V2PushButton;
    QSpinBox* yearV2SpinBox;
    QCheckBox* trackV2CheckBox;
    QSpinBox* trackV2SpinBox;
    QCheckBox* artistV2CheckBox;
    QCheckBox* titleV2CheckBox;
    QCheckBox* albumV2CheckBox;
    QPushButton* editFramesPushButton;
    QPushButton* framesAddPushButton;
    QPushButton* deleteFramesPushButton;
    QLabel* framesTextLabel;
	Kid3ScrollView *scrollView;
	QVBox* rightHalfVBox;
    QHBox* trackV1HBox;
    QHBox* trackV2HBox;
    QVBox* frameButtonVBox;
    QGridLayout* filenameGroupBoxLayout;
    QGridLayout* idV1GroupBoxLayout;
    QGridLayout* idV2GroupBoxLayout;

private slots:
    void dragEnterEvent(QDragEnterEvent * ev);
    void dropEvent(QDropEvent * ev);
};

#endif // ID3FORM_H
