.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH KID3 1 "April 17, 2004"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
kid3 \- Kid3 ID3 Tagger
.SH SYNOPSIS
.B kid3
.RI [ options ] " dir"
.SH DESCRIPTION
 With Kid3, an ID3 tag editor for KDE you can:
.PD
.IP 
* Edit ID3v1.1 tags
.IP
* Edit all ID3v2.3 and ID3v2.4 frames
.IP
* Convert between ID3v1.1, ID3v2.3 and ID3v2.4 tags
.IP
* Edit tags in MP3, Ogg/Vorbis, FLAC, MPC, MP4/AAC, MP2, Speex, TrueAudio, WavPack, WMA, WAV and AIFF files.
.IP
* Edit tags of multiple files, e.g. the artist, album, year and genre of all files of an album typically have the same values and can be set together.
.IP
* Generate tags from filenames
.IP
* Generate filenames from tags
.IP
* Generate playlist files
.IP
* Automatic case conversion and string translation
.IP
* Import and export album data
.IP
* Import from gnudb.org, TrackType.org, MusicBrainz, Discogs, Amazon
.PD 1

.SH OPTIONS
A summary of options are included below.
.TP
.B \-\-help
Show summary of options.
.TP
.B \-\-help\-qt
Show Qt specific options
.TP
.B \-\-help\-kde
Show KDE specific options
.TP
.B \-\-help\-all
Show all options
.TP
.B \-\-author
Show author information
.TP
.B \-v, \-\-version
Show version of program.
.TP
.B \-\-license
Show license information
.SH AUTHOR
.B Kid3
was written by Urs Fleisch <ufleisch@users.sourceforge.net>.
.br
This manual page was written by Aurelien Jarno <aurel32@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
