set(import_SRCS
  import/amazonimporter.cpp
  import/batchimporter.cpp
  import/discogsimporter.cpp
  import/fingerprintcalculator.cpp
  import/freedbimporter.cpp
  import/httpclient.cpp
  import/importclient.cpp
  import/importparser.cpp
  import/jsonparser.cpp
  import/musicbrainzclient.cpp
  import/musicbrainzreleaseimporter.cpp
  import/serverimporter.cpp
  import/textimporter.cpp
  import/trackdatamatcher.cpp
  import/tracktypeimporter.cpp
)

set(import_MOC_HDRS
  import/batchimporter.h
  import/httpclient.h
  import/importclient.h
  import/musicbrainzclient.h
  import/musicbrainzclient.h
  import/musicbrainzclient.h
  import/serverimporter.h
)
